<template>
    <!-- Menu Card -->
    <!--
*  General goal: show User / prompt login.
*  
*  If logged in: (in no particular order)
*     show user name, contributions.
*     # of favorited channels
*     log out button
*     settings page link
*     
*  If not logged in:
*     social login buttons
*     settings page link
*     
                     *  
                     -->
    <v-card flat v-intersect="tryUpdateUser">
        <v-list :dense="inNavDrawer" class="pb-0">
            <v-list-item v-if="user">
                <v-list-item-avatar>
                    <img
                        :src="`https://avatars.dicebear.com/api/jdenticon/${user.id}.svg`"
                        alt="Avatar generated by your user ID"
                    />
                </v-list-item-avatar>
                <v-list-item-content>
                    <v-list-item-title>{{ user.username }}</v-list-item-title>
                    <v-list-item-subtitle>
                        <v-icon small :color="user.discord_id ? 'green lighten-2' : 'grey'">{{
                            icons.mdiDiscord
                        }}</v-icon>
                        &nbsp;
                        <v-icon small :color="user.google_id ? 'green lighten-2' : 'grey'">{{
                            icons.mdiGoogle
                        }}</v-icon>
                        &nbsp;
                        <v-icon small :color="user.twitter_id ? 'green lighten-2' : 'grey'">{{
                            icons.mdiTwitter
                        }}</v-icon>
                        &nbsp;
                    </v-list-item-subtitle>
                    <v-list-item-content class="primary--text d-inline">
                        <v-icon x-small class="d-inline">{{ icons.mdiStarFourPointsOutline }}</v-icon>
                        {{ user.contribution_count }} {{ $t("component.mainNav.points") }}
                    </v-list-item-content>
                </v-list-item-content>
            </v-list-item>
            <!-- <v-list dense> -->
            <v-list-item v-if="!user" to="/login" link>
                <v-list-item-icon>
                    <v-icon>{{ icons.mdiLoginVariant }}</v-icon>
                </v-list-item-icon>
                <v-list-item-title>{{ $t("component.mainNav.login") }}</v-list-item-title>
            </v-list-item>

            <v-divider v-if="user"></v-divider>
            <v-list-item to="/login" v-if="user" link>
                <v-list-item-icon>
                    <v-icon>{{ icons.mdiAccountCircleOutline }}</v-icon>
                </v-list-item-icon>
                <v-list-item-content>
                    <v-list-item-title>
                        {{ $t("component.mainNav.accountSettings") }}
                    </v-list-item-title>
                </v-list-item-content>
            </v-list-item>

            <v-list-item to="/settings" v-if="!noSetting" link>
                <v-list-item-icon>
                    <v-icon>{{ icons.mdiCog }}</v-icon>
                </v-list-item-icon>
                <v-list-item-content>
                    <v-list-item-title>
                        {{ $t("component.mainNav.settings") }}
                    </v-list-item-title>
                </v-list-item-content>
            </v-list-item>
            <v-list-item v-if="user" @click.prevent="logout" link>
                <v-list-item-icon>
                    <v-icon>{{ icons.mdiLogoutVariant }}</v-icon>
                </v-list-item-icon>
                <v-list-item-content>
                    <v-list-item-title>
                        {{ $t("component.mainNav.logout") }}
                    </v-list-item-title>
                </v-list-item-content>
            </v-list-item>
            <!-- </v-list> -->
        </v-list>
    </v-card>
</template>

<script lang="ts">
import * as icons from "@/utils/icons";
import backendApi from "@/utils/backend-api";

export default {
    name: "UserCard",
    data: () => ({
        icons,
    }),
    props: {
        noSetting: {
            type: Boolean,
            default: false,
        },
        inNavDrawer: {
            type: Boolean,
            default: false,
        },
    },
    computed: {
        userdata() {
            return this.$store.state.userdata;
        },
        user() {
            return this.$store.state.userdata.user;
        },
    },
    methods: {
        hashCode(x) {
            let hash = 0;
            // eslint-disable-next-line no-plusplus
            for (let i = 0; i < x.length; i++) {
                const character = x.charCodeAt(i);
                // eslint-disable-next-line no-bitwise
                hash = (hash << 5) - hash + character;
                // eslint-disable-next-line no-bitwise
                hash &= hash; // Convert to 32bit integer
            }
            return hash;
        },
        logout() {
            this.$store.dispatch("logout");
        },
        async tryUpdateUser() {
            // TODO(jprochazk): this doesn't have to be on window
            // it'd be better to have it on `$store` or in `data`, but it being on window doesn't break anything.
            // @ts-ignore
            if (this.userdata && this.userdata.jwt && Date.now() - (window.lastUserCheck || 0) > 60000) {
                // @ts-ignore
                window.lastUserCheck = Date.now();
                this.forceUserUpdate();
            }
        },
        async forceUserUpdate() {
            const check = await backendApi.loginIsValid(this.userdata.jwt);
            if (check === false) {
                this.$store.dispatch("logout");
            } else if (check.data && check.data.id) {
                this.$store.commit("setUser", { user: check.data, jwt: this.userdata.jwt });
            }
        },
    },
};
</script>

<style></style>
