// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    AppFrame: typeof import('./src/components/AppFrame.vue')['default']
    Button: typeof import('./src/stories/Button.vue')['default']
    ChannelImg: typeof import('./src/components/channel/common/ChannelImg.vue')['default']
    GoogleSignInButton: typeof import('./src/components/login/GoogleSignInButton.vue')['default']
    HList: typeof import('./src/components/core/HList.vue')['default']
    Home: typeof import('./src/views/Home.vue')['default']
    KitchenSink: typeof import('./src/views/KitchenSink.vue')['default']
    LiveTranslations: typeof import('./src/components/tldex/client/LiveTranslations.vue')['default']
    Login: typeof import('./src/views/Login.vue')['default']
    Logo: typeof import('./src/components/frame/Logo.vue')['default']
    MainNav: typeof import('./src/components/nav/MainNav.vue')['default']
    NavDrawer: typeof import('./src/components/nav/NavDrawer.vue')['default']
    OrgSelector: typeof import('./src/components/frame/OrgSelector.vue')['default']
    Page: typeof import('./src/stories/Page.vue')['default']
    Profile: typeof import('./src/views/Profile.vue')['default']
    TLClient: typeof import('./src/components/tldex/editor/TLClient.vue')['default']
    TLScriptEditor: typeof import('./src/components/tldex/editor/TLScriptEditor.vue')['default']
    TodoList: typeof import('./src/components/TodoList.vue')['default']
    TranslationClient: typeof import('./src/views/TranslationClient.vue')['default']
    TranslationScripter: typeof import('./src/views/TranslationScripter.vue')['default']
    UserCard: typeof import('./src/components/login/UserCard.vue')['default']
    VideoCard: typeof import('./src/components/video/card/VideoCard.vue')['default']
    VideoCardGrid: typeof import('./src/components/video/card/VideoCardGrid.vue')['default']
    VideoCardLiveDuration: typeof import('./src/components/video/card/VideoCardLiveDuration.vue')['default']
    VideoCardMenu: typeof import('./src/components/video/card/VideoCardMenu.vue')['default']
    VideoCardStatus: typeof import('./src/components/video/card/VideoCardStatus.vue')['default']
    VideoCardText: typeof import('./src/components/video/card/VideoCardText.vue')['default']
    VideoThumbnail: typeof import('./src/components/video/card/VideoThumbnail.vue')['default']
  }
}

export {}
