<template>
  <!-- <div id="nav-container"> -->
  <!-- watch page nav drawer is temporary, but causes layout shifting from hiding/unhiding -->
  <!-- create two different instances as a work around -->

  <!--* nav drawer is for the left --->
  <!-- <BottomNav
      v-if="isSmOrDown"
      :pages="pages.filter((page) => !page.collapsible)"
      :active="!isWatchPage"
    /> -->
  <!--* bottom bar --->

  <div
    v-show="showTopBar"
    id="top-bar"
    :app="showTopBar"
    class="navbar sticky top-0 z-10 h-[56px] min-h-[56px] border-b border-bgColor-100 bg-bgColor pb-0"
    style="align-self: start"
  >
    <!--=============================== Top Bar (Regular View) =============================-->
    <template v-if="!isMobile || (isMobile && !searchBarExpanded)">
      <!--================= Logo & Search Bar (Space permitting) ================-->
      <div class="mr-2 cursor-pointer" @click.stop="$emit('toggleSidebar')">
        <logo v-if="isSmOrDown" width="32" height="32" :loading="loading > 0" />
        <div v-else class="i-ion:menu h-6 w-6" />
      </div>
      <div class="mr-2 flex shrink-0 flex-row items-center gap-2">
        <router-link
          v-if="!isSmOrDown"
          :to="{ name: settings.defaultOpen || 'Home' }"
        >
          <logo width="32" height="32" :loading="loading > 0" />
        </router-link>
        <OrgSelector
          @changed="(org: Org, close?: Function) => {site.currentOrg = org; close && close();}"
        />
      </div>
      <!-- </v-toolbar-title> -->
      <!-- <SearchBar
          v-if="!isMobile"
          key="main-search-bar"
          class="mx-auto height-40px"
        /> -->
      <SearchBar4
        v-if="!isMobile"
        key="main-search-bar2"
        class="height-40px mx-auto"
      />

      <!--================= Account [👤] Button (Desktop Only) ================-->

      <playlist-button
        class="mr-2 flex-shrink"
        @click="playlistDrawer = !playlistDrawer"
      />
      <h-menu v-if="!isMobile" placement="bottom-end">
        <template #activator="{ props }">
          <div
            v-bind="props"
            class="btn btn-ghost btn-square mr-2 text-2xl"
            style="width: 3rem; height: 3rem; min-height: 3rem"
          >
            <h-icon
              v-if="!(site.user && site.user)"
              class="i-mdi:account-circle-outline"
            />
            <img
              v-else
              class="h-10 w-10 rounded-full"
              :src="`https://avatars.dicebear.com/api/jdenticon/${site.user.id}.svg`"
              alt="Avatar generated by your user ID"
            />
          </div>
        </template>

        <!------- USER CARD ------->
        <user-card />
        <!------- END USER CARD ------->
      </h-menu>

      <!--================= Search [🔍] Button (Mobile Only) ================-->

      <h-btn
        v-if="isMobile"
        icon="i-material-symbols:search-rounded"
        class="btn-icon"
        @click="searchBarExpanded = true"
      />
    </template>

    <!--=========================== END OF Regular View ===========================-->

    <!--===================== Expanded Search Bar (Mobile Only) =======================-->

    <template v-else>
      <!-- <v-app-bar-nav-icon
        style="margin-left: 0px"
        @click="searchBarExpanded = false"
      >
        <v-icon>some close button icon</v-icon>
      </v-app-bar-nav-icon>
      <SearchBar key="main-search-bar" :autofocus="isMobile" class="mr-3" /> -->
    </template>

    <!--=================== END OF Expanded Search (Mobile Only) =======================-->
    <div
      :class="'primary'"
      style="
        position: absolute;
        top: calc(-1 * env(safe-area-inset-top));
        left: 0px;
        right: 0px;
        width: 100%;
        height: env(safe-area-inset-top);
        z-index: 300;
      "
    >
      <!-- this is just the element that covers up the notch. don't worry about it. -->
    </div>
  </div>
  <!-- <NavDrawer
      v-model="navDrawer"
      :pages="pages"
      :temporary="isMdOrDown || isWatchPage"
      :expand="navbarExpanded"
      @expand="navbarExpanded = !navbarExpanded"
    /> -->

  <!-- <v-navigation-drawer
      id="playlistDrawer"
      v-model="playlistDrawer"
      location="right"
      temporary
      :width="360"
      class="py-2 pl-2"
    >
      <current-playlist-card />
    </v-navigation-drawer> -->
  <!-- </div> -->
</template>

<script lang="ts">
import { useSiteStore } from "@/stores/site";
import { useSettingsStore } from "@/stores/settings";
import { useIsFetching } from "@tanstack/vue-query";
import { useDisplay } from "@/hooks/common/useDisplay";

export default defineComponent({
  components: {},
  emits: ["toggleSidebar"],
  setup() {
    const site = useSiteStore();
    const settings = useSettingsStore();
    const display = useDisplay();
    const loading = useIsFetching();

    const isMobile = display.mobile;
    const isSmOrDown = display.smaller("sm");
    const isMdOrDown = display.smaller("lg");
    return {
      site,
      display,
      isMobile,
      isSmOrDown,
      isMdOrDown,
      settings,
      loading,
    };
  },
  data() {
    return {
      favoritesExpanded: false,
      searchBarExpanded: false,
      navbarExpanded: false,

      navDrawer: true,
      playlistDrawer: false,
    };
  },
  computed: {
    showTopBar() {
      if (this.isMultiView) return false;
      if (this.isMobile && this.isWatchPage) {
        return false;
      }
      if (
        this.$route.name === "tlclient" ||
        this.$route.name === "scripteditor"
      ) {
        return false;
      }
      return true;
    },
    isWatchPage() {
      return [
        "watch_id",
        "watch",
        "edit_video",
        "multiview",
        "tlclient",
        "scripteditor",
      ].includes(this.$route.name as any);
    },
    isMultiView() {
      return this.$route.name === "multiview";
    },
  },
  watch: {
    // toggle navdrawer when navigating between watch pages on desktop
    isWatchPage() {
      if (this.isMobile) return;
      this.navDrawer = !this.isWatchPage;
    },
  },
  created() {
    if (this.site.guide.firstVisit) {
      setTimeout(() => {
        this.site.guide.firstVisit = false;
      }, 30000);
    }

    // always pop out nav drawer if it's not watch page or collapsed
    if (
      !window.location.pathname.match("^/watch|^/multiview|^/infinite") &&
      !this.isMdOrDown
    ) {
      this.navDrawer = true;
    }
  },
});
</script>
<style>
#playlistDrawer .v-navigation-drawer__content {
  overflow: hidden;
}
</style>
<style scoped lang="scss">
@keyframes rotation {
  from {
    transform: rotate(0deg);
  }

  to {
    transform: rotate(359deg);
  }
}

#top-bar {
  /* background-color: #2b79ad !important; */
  // TODO: this thing
  /* padding-left: min(calc(env(safe-area-inset-left)), 30px);
  padding-right: min(calc(env(safe-area-inset-right)), 30px); */
  /* padding-top: min(calc(env(safe-area-inset-top) / 2), 30px); */
  /* height: calc(env(safe-area-inset-top,0px) + 30px); */
  padding-top: 0px;
  margin-top: env(safe-area-inset-top, 0px) !important;
  overflow: visible;
}

/* #top-bar.v-toolbar--extended {
  height: 56px !important;
} */

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s ease;
}

.fade-enter,
.fade-leave-to {
  opacity: 0;
}

.main-playlist-border {
  border: 2px solid var(--v-primary-base);
  border-radius: 8px;
}

.theme--dark .main-playlist-border {
  box-shadow: 0px 6px 12px -7px var(--v-primary-darken2);
}

.theme--light .main-playlist-border {
  box-shadow: 0px 6px 12px -7px var(--v-primary-lighten2);
}
</style>
