<template>
  <div id="nav-container">
    <!-- watch page nav drawer is temporary, but causes layout shifting from hiding/unhiding -->
    <!-- create two different instances as a work around -->

    <!--* nav drawer is for the left --->
    <BottomNav
      v-if="isMobile"
      :pages="pages.filter((page) => !page.collapsible)"
      :active="!isWatchPage"
    />
    <!--* bottom bar --->

    <v-app-bar
      v-show="showTopBar"
      id="top-bar"
      :app="showTopBar"
      clipped-left
      clipped-right
      flat
      height="56"
      style="border-bottom: 1px solid rgba(255, 255, 255, 0.12)"
      class="bg-base-100"
    >
      <!--=============================== Top Bar (Regular View) =============================-->

      <template v-if="!isMobile || (isMobile && !searchBarExpanded)">
        <!--================= Logo & Search Bar (Space permitting) ================-->
        <v-app-bar-nav-icon
          :icon="icons.mdiMenu"
          @click.stop="navDrawer = !navDrawer"
        ></v-app-bar-nav-icon>
        <div class="flex flex-row items-center gap-2 ml-md-2">
          <router-link :to="{ name: settings.defaultOpen || 'Home' }">
            <logo v-if="!isMobile" width="32" height="32" :loading="loading" />
          </router-link>
          <OrgSelector
            @changed="(org: Org, close?: Function) => {site.currentOrg = org; close && close();}"
          />
        </div>
        <!-- </v-toolbar-title> -->
        <SearchBar
          v-if="!isMobile"
          key="main-search-bar"
          class="mx-auto height-40px"
        />

        <!--================= Account [👤] Button (Desktop Only) ================-->

        <!-- Playlist Feature disabled for now -->
        <!-- <ResponsiveMenu :close-on-content-click="false" offset-y
                    :item-count="playlist.active.videos.length || 0" content-class="main-playlist-border">
                    <template #activator="{ on, attrs }">
                        <v-btn v-bind="attrs" icon :class="{ 'ml-auto': isMobile }" v-on="on">
                            <v-icon>{{ icons.mdiPlaylistPlay }}</v-icon>
                        </v-btn>
                    </template>
                    <edit-playlist>
                        <div class="pt-2 pl-2">
                            <span class="text-overline secondary--text">Current Playlist</span>&emsp;
                            <router-link to="/playlists" class="text-caption">
                                (more)
                            </router-link>
                        </div>
                    </edit-playlist>
                </ResponsiveMenu> -->
        <v-menu v-if="!isMobile" left offset-y transition="slide-y-transition">
          <template #activator="{ props }">
            <v-btn icon v-bind="props" class="ml-auto">
              <v-icon v-if="!(site.user && site.user)">
                {{ icons.mdiAccountCircleOutline }}
              </v-icon>
              <v-avatar v-else size="40">
                <img
                  :src="`https://avatars.dicebear.com/api/jdenticon/${site.user.id}.svg`"
                  alt="Avatar generated by your user ID"
                />
              </v-avatar>
            </v-btn>
          </template>

          <!------- USER CARD ------->
          <user-card />
          <!------- END USER CARD ------->
        </v-menu>

        <!--================= Search [🔍] Button (Mobile Only) ================-->

        <v-btn v-if="isMobile" icon @click="searchBarExpanded = true">
          <v-icon>{{ icons.mdiMagnify }}</v-icon>
        </v-btn>
      </template>

      <!--=========================== END OF Regular View ===========================-->

      <!--===================== Expanded Search Bar (Mobile Only) =======================-->

      <template v-else>
        <v-app-bar-nav-icon
          class="backButton"
          @click="searchBarExpanded = false"
        >
          <v-icon>{{ icons.mdiClose }}</v-icon>
        </v-app-bar-nav-icon>
        <SearchBar key="main-search-bar" :autofocus="isMobile" />
      </template>

      <!--=================== END OF Expanded Search (Mobile Only) =======================-->
      <div
        :class="'primary'"
        style="
          position: absolute;
          top: calc(-1 * env(safe-area-inset-top));
          left: 0px;
          right: 0px;
          width: 100%;
          height: env(safe-area-inset-top);
          z-index: 300;
        "
      >
        <!-- this is just the element that covers up the notch. don't worry about it. -->
      </div>

      <!-- Extension Slot for mobile v-tabs -->
      <!-- Disable onScroll when ext is disabled. onScroll hooks on to window, so it can live anywhere -->
      <!-- <span v-if="!disableExt" v-scroll="onScroll" /> -->
      <!-- <template v-if="!disableExt" #extension> -->
      <!-- <v-slide-y-transition> -->
      <!-- v-tabs are teleported here from their respective view -->
      <!-- <portal-target v-if="showExt" name="mainNavExt" slim /> -->
      <!-- </v-slide-y-transition> -->
      <!-- </template> -->
    </v-app-bar>
    <NavDrawer
      v-model="navDrawer"
      :pages="pages"
      :temporary="isMobile || isWatchPage"
      :expand="navbarExpanded"
      @expand="navbarExpanded = !navbarExpanded"
    >
      <!-- <NavDrawer :pages="pages" v-model="drawer2" v-if="isMobile || isWatchPage"  -->
      <template v-if="isMobile">
        <!-- <InstallPrompt /> -->
        <user-card no-setting in-nav-drawer style="background-color: inherit" />
        <v-divider />
      </template>
    </NavDrawer>
  </div>
</template>

<script lang="ts">
import { musicdexURL } from "@/utils/consts";
import { useSiteStore } from "@/stores/site";
import { useDisplay } from "vuetify";
import { useSettingsStore } from "@/stores/settings";
import { useIsFetching } from "vue-query";

export default defineComponent({
  components: {},
  setup() {
    const site = useSiteStore();
    const settings = useSettingsStore();
    const display = useDisplay();
    const loading = useIsFetching();

    const isMobile = display.mobile;

    return { site, display, isMobile, settings, loading };
  },
  data() {
    return {
      favoritesExpanded: false,
      searchBarExpanded: false,
      navbarExpanded: false,

      navDrawer: true,
    };
  },
  computed: {
    showTopBar() {
      if (this.isMultiView) return false;
      if (this.isMobile && this.isWatchPage) {
        return false;
      }
      if (
        this.$route.name === "tlclient" ||
        this.$route.name === "scripteditor"
      ) {
        return false;
      }
      return true;
    },
    isWatchPage() {
      return [
        "watch_id",
        "watch",
        "edit_video",
        "multiview",
        "tlclient",
        "scripteditor",
      ].includes(this.$route.name as any);
    },
    isMultiView() {
      return this.$route.name === "multiview";
    },
    pages() {
      return [
        {
          routeName: "Home_Org",
          name: this.$t("component.mainNav.home"),
          path: "/",
          icon: "i-material-symbols:home-storage-rounded",
        },
        {
          name: this.$t("component.mainNav.favorites"),
          path: "/favorites",
          icon: "i-material-symbols:favorite-rounded",
        },
        {
          name: this.$t("component.mainNav.channels"),
          path: `/channels`,
          icon: "i-ion:people",
          routeName: "Channels_Org",
        },
        {
          name: this.$t("component.mainNav.playlist"),
          path: "/playlists",
          icon: "i-material-symbols:playlist-play-rounded",
          divider: true,
        },
        {
          name: this.$t("component.mainNav.multiview"),
          path: "/multiview",
          icon: "i-clarity:grid-chart-solid",
          collapsible: true,
        },
        {
          name: "Musicdex",
          path: musicdexURL,
          // icon: this.icons.mdiMusic,
          collapsible: true,
          divider: true,
        },
        {
          name: this.$t("component.mainNav.about"),
          path: "/about",
          icon: "i-ion:information-circle-outline",
          collapsible: true,
        },
        {
          name: this.$t("component.mainNav.settings"),
          path: "/settings",
          icon: "i-material-symbols:settings-rounded",
          collapsible: true,
        },
        {
          name: "TL client",
          path: "/tlclient",
          icon: this.icons.mdiTypewriter,
          collapsible: true,
          extra: true,
        },
        {
          name: "Script Editor",
          path: "/scripteditor",
          icon: this.icons.mdiNoteEdit,
          collapsible: true,
          extra: true,
        },
        {
          name: "Script Manager",
          path: "/scriptmanager",
          icon: this.icons.mdiFileDocumentMultiple,
          collapsible: true,
          extra: true,
        },
        {
          name: "Relay Bot Setting",
          path: "/relaybot",
          icon: this.icons.mdiRobot,
          collapsible: true,
          extra: true,
        },
      ];
    },
  },
  watch: {
    // toggle navdrawer when navigating between watch pages on desktop
    isWatchPage() {
      if (this.isMobile) return;
      this.navDrawer = !this.isWatchPage;
    },
    // if user is flipping between mobile/desktop breakpoints, keep navdrawer closed
    isMobile() {
      this.navDrawer = false;
    },
  },
  created() {
    if (this.site.guide.firstVisit) {
      setTimeout(() => {
        this.site.guide.firstVisit = false;
      }, 30000);
    }

    // always pop out nav drawer if it's not watch page or collapsed
    if (
      !window.location.pathname.match("^/watch|^/multiview|^/infinite") &&
      !this.isMobile &&
      !this.$vuetify.display.md
    ) {
      this.navDrawer = true;
    }
  },
});
</script>

<style scoped lang="scss">
@keyframes rotation {
  from {
    transform: rotate(0deg);
  }

  to {
    transform: rotate(359deg);
  }
}

#top-bar {
  /* background-color: #2b79ad !important; */
  // TODO: this thing
  /* padding-left: min(calc(env(safe-area-inset-left)), 30px);
  padding-right: min(calc(env(safe-area-inset-right)), 30px); */
  /* padding-top: min(calc(env(safe-area-inset-top) / 2), 30px); */
  /* height: calc(env(safe-area-inset-top,0px) + 30px); */
  padding-top: 0px;
  margin-top: env(safe-area-inset-top, 0px) !important;
}

#top-bar.v-toolbar--extended {
  height: 56px !important;
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s ease;
}

.fade-enter,
.fade-leave-to {
  opacity: 0;
}

.main-playlist-border {
  border: 2px solid var(--v-primary-base);
  border-radius: 8px;
}

.theme--dark .main-playlist-border {
  box-shadow: 0px 6px 12px -7px var(--v-primary-darken2);
}

.theme--light .main-playlist-border {
  box-shadow: 0px 6px 12px -7px var(--v-primary-lighten2);
}
</style>
