<template>
  <p v-for="n in 15" :key="n">
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit nihil
    praesentium molestias a adipisci, dolore vitae odit, quidem consequatur
    optio voluptates asperiores pariatur eos numquam rerum delectus commodi
    perferendis voluptate?
  </p>


  <v-card width="400">
    <v-card-header>
      <v-card-header-text>
        <v-card-title>This is a title</v-card-title>
        <v-card-subtitle>This is a subtitle</v-card-subtitle>
      </v-card-header-text>
    </v-card-header>

    <v-card-text>
      This is content
      <v-chip class="ma-2">
        Default
      </v-chip>

      <v-chip class="ma-2" color="primary">
        Primary
      </v-chip>

      <v-chip class="ma-2" color="secondary">
        Secondary
      </v-chip>

      <v-chip class="ma-2" color="pink" label text-color="white">
        <v-icon start icon="mdi-label" />
        Tags
      </v-chip>

      <v-chip class="ma-2" color="green" text-color="white">
        Green Chip
      </v-chip>
      <hr>
      <div class="avatar online">
        <div class="w-24 rounded-full">
          <img src="https://api.lorem.space/image/face?hash=28212">
        </div>
      </div>
      <div class="ml-4 rounded-full avatar ring ring-error ring-offset-base-100 ring-offset-2">
        <div class="w-24 rounded-full">
          <img src="https://api.lorem.space/image/face?hash=40361">
        </div>
      </div>
    </v-card-text>
    <v-card-actions>
      <div class="btn-group">
        <button class="btn btn-active btn-sm">
          Button
        </button>
        <button class="btn btn-sm">
          Button
        </button>
        <button class="btn btn-sm">
          Button
        </button>
      </div>
      <v-btn>Button</v-btn>
      <v-menu left offset-y transition="slide-y-transition">
        <template #activator="{ props }">
          <v-btn icon v-bind="props" class="ml-2">
            <v-avatar size="40">
              <img :src="`https://avatars.dicebear.com/api/jdenticon/1423.svg`" alt="Avatar generated by your user ID">
            </v-avatar>
          </v-btn>
        </template>

        <!------- USER CARD ------->
        <v-sheet>
          <div class="btn-group">
            <button class="btn btn-active btn-sm">
              Button
            </button>
            <button class="btn btn-sm">
              Button
            </button>
            <button class="btn btn-sm">
              Button
            </button>
          </div>
        </v-sheet>
        <!------- END USER CARD ------->
      </v-menu>
    </v-card-actions>
  </v-card>

  <v-card width="500">
    <ul class="p-2 overflow-y-auto menu bg-base-300 text-base-content">
      <li><a>Sidebar Item 1</a></li>
      <li><a>Sidebar Item 2</a></li>
    </ul>
  </v-card>
</template>

<style>

</style>