/**------------------------------------------------------------------------------------------------
 * *                                    Icons container
 *
 *   Importing the most commonly used mdi/js icons.
 *------------------------------------------------------------------------------------------------* */
export {
    mdiAccountBoxMultiple,
    mdiAccountCircleOutline,
    mdiAnimationPlay,
    mdiArrowLeft,
    mdiClipboardPlusOutline,
    mdiClipboardArrowUpOutline,
    mdiClose,
    mdiCog,
    mdiDatabaseOff,
    mdiDelete,
    mdiDiscord,
    mdiDotsVertical,
    mdiEarth, // for language
    mdiGoogle,
    mdiHeart,
    mdiHelpCircle,
    mdiHome,
    mdiLoginVariant,
    mdiLogoutVariant,
    mdiOpenInNew,
    mdiMagnify,
    mdiMenu,
    mdiMusic,
    mdiPencil, // for changing language
    mdiPlay,
    mdiPlayNetwork,
    mdiPlaylistMusic,
    mdiPlaylistPlay,
    mdiPlaylistPlus,
    mdiRefresh,
    mdiStarFourPointsOutline,
    mdiTypewriter,
    mdiTranslate,
    mdiTwitter,
    mdiYoutube,
    mdiMenuDown,
    mdiPlusBox,
    mdiCheck,
    mdiGridLarge,
    mdiChevronDown,
    mdiChevronUp,
    mdiChevronLeft,
    mdiChevronRight,
    mdiFullscreen,
    mdiViewDashboard,
    mdiViewComfy,
    mdiViewGrid,
    mdiViewModule,
    mdiVolumeHigh,
    mdiVolumeMute,
    mdiFlag,
    mdiStar,
    mdiCalendar,
    mdiTheater,
    mdiSelectMultiple,
    mdiSelectAll,
    mdiSelectOff,
    mdiContentSaveEdit,
    mdiPinOutline,
    mdiFileDocumentMultiple,
    mdiRobot,
    mdiNoteEdit,
    mdiClockAlertOutline,
    mdiSchool,
} from "@mdi/js";

export const ytChat = "M20,2H4C2.9,2,2,2.9,2,4v18l4-4h14c1.1,0,2-0.9,2-2V4C22,2.9,21.1,2,20,2zM9.9,10.8v3.8h-2v-3.8L5.1,6.6h2.4l1.4,2.2 l1.4-2.2h2.4L9.9,10.8zM18.9,8.6h-2v6h-2v-6h-2v-2h6V8.6z";
export const tlChat = "M20,2H4C2.9,2,2,2.9,2,4v18l4-4h14c1.1,0,2-0.9,2-2V4C22,2.9,21.1,2,20,2z M4,10h4v2H4V10zM14,16H4v-2h10V16z M20,16h-4v-2 h4V16z M20,12H10v-2h10V12z";
