/**------------------------------------------------------------------------------------------------
 * *                                    Icons container
 *
 *   Importing the most commonly used mdi/js icons.
 *------------------------------------------------------------------------------------------------* */
export {
    mdiAccountBoxMultiple,
    mdiAccountCircleOutline,
    mdiAnimationPlay,
    mdiArrowLeft,
    mdiClipboardPlusOutline,
    mdiClose,
    mdiCog,
    mdiDatabaseOff,
    mdiDelete,
    mdiDiscord,
    mdiDotsVertical,
    mdiEarth, // for language
    mdiGoogle,
    mdiHeart,
    mdiHelpCircle,
    mdiHome,
    mdiLoginVariant,
    mdiLogoutVariant,
    mdiOpenInNew,
    mdiMagnify,
    mdiMapMarker,
    mdiMenu,
    mdiMessageCogOutline,
    mdiMusic,
    mdiPencil, // for changing language
    mdiPlay,
    mdiPlaylistMusic,
    mdiPlaylistPlay,
    mdiPlaylistPlus,
    mdiRefresh,
    mdiStarFourPointsOutline,
    mdiTranslate,
    mdiTwitter,
    mdiYoutube,
    mdiMenuDown,
    mdiPlusBox,
    mdiCheck,
    mdiGridLarge,
    mdiGrid,
    mdiSquareOutline,
    mdiChevronDown,
    mdiChevronUp,
    mdiChevronLeft,
    mdiChevronRight,
    mdiFullscreen,
    mdiViewDashboard,
    mdiVolumeHigh,
    mdiVolumeMute,
    mdiFlag,
    mdiStar,
    mdiCalendar,
} from "@mdi/js";
