export const desktopPresets = Object.freeze([
    {
        layout: [
            {
                x: 0,
                y: 0,
                w: 19,
                h: 24,
                i: 0,
            },
            {
                x: 19,
                y: 0,
                w: 5,
                h: 24,
                i: 1,
            },
        ],
        name: "Side Chat 1",
        emptyCells: 1,
        content: {
            1: {
                type: "chat",
            },
        },
    },
    {
        layout: [
            {
                x: 0,
                y: 0,
                w: 17,
                h: 12,
                i: 0,
            },
            {
                x: 0,
                y: 12,
                w: 17,
                h: 12,
                i: 1,
            },
            {
                x: 17,
                y: 0,
                w: 7,
                h: 24,
                i: 2,
            },
        ],
        name: "Side Chat 2",
        emptyCells: 2,
        content: {
            2: {
                type: "chat",
            },
        },
    },
    {
        layout: [
            {
                x: 0,
                y: 0,
                w: 12,
                h: 24,
                i: 0,
            },
            {
                x: 12,
                y: 0,
                w: 12,
                h: 12,
                i: 1,
            },
            {
                x: 12,
                y: 12,
                w: 12,
                h: 12,
                i: 2,
            },
        ],
        name: "p1s2",
        emptyCells: 3,
        content: {},
    },
    {
        layout: [
            {
                x: 0,
                y: 0,
                w: 12,
                h: 12,
                i: 0,
            },
            {
                x: 0,
                y: 12,
                w: 12,
                h: 12,
                i: 1,
            },
            {
                x: 12,
                y: 0,
                w: 12,
                h: 12,
                i: 2,
            },
            {
                x: 12,
                y: 12,
                w: 12,
                h: 12,
                i: 3,
            },
        ],
        name: "2 x 2",
        emptyCells: 4,
        content: {},
    },
    {
        layout: [
            {
                x: 0,
                y: 0,
                w: 8,
                h: 12,
                i: 0,
            },
            {
                x: 0,
                y: 12,
                w: 8,
                h: 12,
                i: 1,
            },
            {
                x: 8,
                y: 0,
                w: 8,
                h: 12,
                i: 2,
            },
            {
                x: 8,
                y: 12,
                w: 8,
                h: 12,
                i: 3,
            },
            {
                x: 16,
                y: 0,
                w: 8,
                h: 12,
                i: 4,
            },
            {
                x: 16,
                y: 12,
                w: 8,
                h: 12,
                i: 5,
            },
        ],
        name: "2 x 3",
        emptyCells: 6,
        content: {},
    },
    {
        layout: [
            {
                x: 0,
                y: 0,
                w: 8,
                h: 8,
                i: 0,
            },
            {
                x: 0,
                y: 8,
                w: 8,
                h: 8,
                i: 1,
            },
            {
                x: 0,
                y: 16,
                w: 8,
                h: 8,
                i: 2,
            },
            {
                x: 8,
                y: 0,
                w: 8,
                h: 8,
                i: 3,
            },
            {
                x: 8,
                y: 8,
                w: 8,
                h: 8,
                i: 4,
            },
            {
                x: 8,
                y: 16,
                w: 8,
                h: 8,
                i: 5,
            },
            {
                x: 16,
                y: 0,
                w: 8,
                h: 8,
                i: 6,
            },
            {
                x: 16,
                y: 8,
                w: 8,
                h: 8,
                i: 7,
            },
            {
                x: 16,
                y: 16,
                w: 8,
                h: 8,
                i: 8,
            },
        ],
        name: "3 x 3",
        emptyCells: 9,
        content: {},
    },
    {
        layout: [
            {
                x: 18,
                y: 0,
                w: 6,
                h: 24,
                i: 0,
            },
            {
                x: 0,
                y: 0,
                w: 9,
                h: 12,
                i: 1,
            },
            {
                x: 0,
                y: 12,
                w: 9,
                h: 12,
                i: 2,
            },
            {
                x: 9,
                y: 0,
                w: 9,
                h: 12,
                i: 3,
            },
            {
                x: 9,
                y: 12,
                w: 9,
                h: 12,
                i: 4,
            },
        ],
        name: "Side Chat 4",
        content: {
            0: {
                type: "chat",
            },
        },
    },
    {
        layout: [
            {
                x: 0,
                y: 0,
                w: 16,
                h: 16,
                i: 0,
            },
            {
                x: 0,
                y: 16,
                w: 8,
                h: 8,
                i: 1,
            },
            {
                x: 8,
                y: 16,
                w: 8,
                h: 8,
                i: 2,
            },
            {
                x: 16,
                y: 0,
                w: 8,
                h: 8,
                i: 3,
            },
            {
                x: 16,
                y: 8,
                w: 8,
                h: 8,
                i: 4,
            },
            {
                x: 16,
                y: 16,
                w: 8,
                h: 8,
                i: 5,
            },
        ],
        name: "p1s5",
        emptyCells: 6,
        content: {},
    },
    {
        layout: [
            {
                x: 0,
                y: 0,
                w: 14,
                h: 12,
                i: 0,
            },
            {
                x: 0,
                y: 12,
                w: 14,
                h: 12,
                i: 1,
            },
            {
                x: 14,
                y: 0,
                w: 5,
                h: 24,
                i: 2,
            },
            {
                x: 19,
                y: 0,
                w: 5,
                h: 24,
                i: 3,
            },
        ],
        name: "2 Video, 2 Chat",
        content: {
            2: {
                type: "chat",
            },
            3: {
                type: "chat",
            },
        },
    },
    {
        layout: [
            {
                x: 0,
                y: 0,
                w: 12,
                h: 12,
                i: 0,
            },
            {
                x: 0,
                y: 12,
                w: 12,
                h: 12,
                i: 1,
            },
            {
                x: 12,
                y: 0,
                w: 12,
                h: 12,
                i: 2,
            },
            {
                x: 12,
                y: 12,
                w: 6,
                h: 12,
                i: 3,
            },
            {
                x: 18,
                y: 12,
                w: 6,
                h: 12,
                i: 4,
            },
        ],
        name: "3 Video, 2 Chat",
        content: {
            3: {
                type: "chat",
            },
            4: {
                type: "chat",
            },
        },
    },
    {
        layout: [
            {
                x: 0,
                y: 0,
                w: 12,
                h: 11,
                i: 0,
            },
            {
                x: 12,
                y: 0,
                w: 12,
                h: 11,
                i: 1,
            },
            {
                x: 0,
                y: 11,
                w: 6,
                h: 7,
                i: 2,
            },
            {
                x: 6,
                y: 11,
                w: 6,
                h: 7,
                i: 3,
            },
            {
                x: 12,
                y: 11,
                w: 6,
                h: 7,
                i: 4,
            },
            {
                x: 18,
                y: 11,
                w: 6,
                h: 7,
                i: 5,
            },
            {
                x: 0,
                y: 18,
                w: 6,
                h: 6,
                i: 6,
            },
            {
                x: 6,
                y: 18,
                w: 6,
                h: 6,
                i: 7,
            },
            {
                x: 12,
                y: 18,
                w: 6,
                h: 6,
                i: 8,
            },
            {
                x: 18,
                y: 18,
                w: 6,
                h: 6,
                i: 9,
            },
        ],
        name: "Among Us 1",
        content: {},
    },
    {
        layout: [
            {
                x: 0,
                y: 0,
                w: 10,
                h: 11,
                i: 0,
            },
            {
                x: 10,
                y: 0,
                w: 10,
                h: 11,
                i: 1,
            },
            {
                x: 20,
                y: 0,
                w: 4,
                h: 24,
                i: 2,
            },
            {
                x: 0,
                y: 11,
                w: 5,
                h: 7,
                i: 3,
            },
            {
                x: 5,
                y: 11,
                w: 5,
                h: 7,
                i: 4,
            },
            {
                x: 10,
                y: 11,
                w: 5,
                h: 7,
                i: 5,
            },
            {
                x: 15,
                y: 11,
                w: 5,
                h: 7,
                i: 6,
            },
            {
                x: 0,
                y: 18,
                w: 5,
                h: 6,
                i: 7,
            },
            {
                x: 5,
                y: 18,
                w: 5,
                h: 6,
                i: 8,
            },
            {
                x: 10,
                y: 18,
                w: 5,
                h: 6,
                i: 9,
            },
            {
                x: 15,
                y: 18,
                w: 5,
                h: 6,
                i: 10,
            },
        ],
        name: "Among Us 2",
        content: {
            2: {
                type: "chat",
            },
        },
    },
    {
        layout: [
            {
                x: 0,
                y: 0,
                w: 18,
                h: 17,
                i: 0,
            },
            {
                x: 18,
                y: 0,
                w: 6,
                h: 24,
                i: 1,
            },
            {
                x: 0,
                y: 17,
                w: 6,
                h: 7,
                i: 2,
            },
            {
                x: 6,
                y: 17,
                w: 6,
                h: 7,
                i: 3,
            },
            {
                x: 12,
                y: 17,
                w: 6,
                h: 7,
                i: 4,
            },
        ],
        name: "Sports Fes 1",
        content: {
            1: {
                type: "chat",
            },
        },
    },
    {
        layout: [
            {
                x: 0,
                y: 0,
                w: 12,
                h: 12,
                i: 0,
            },
            {
                x: 18,
                y: 0,
                w: 6,
                h: 24,
                i: 1,
            },
            {
                x: 0,
                y: 12,
                w: 6,
                h: 6,
                i: 2,
            },
            {
                x: 0,
                y: 18,
                w: 6,
                h: 6,
                i: 3,
            },
            {
                x: 6,
                y: 12,
                w: 6,
                h: 6,
                i: 4,
            },
            {
                x: 6,
                y: 18,
                w: 6,
                h: 6,
                i: 5,
            },
            {
                x: 12,
                y: 0,
                w: 6,
                h: 6,
                i: 6,
            },
            {
                x: 12,
                y: 6,
                w: 6,
                h: 6,
                i: 7,
            },
            {
                x: 12,
                y: 12,
                w: 6,
                h: 6,
                i: 8,
            },
            {
                x: 12,
                y: 18,
                w: 6,
                h: 6,
                i: 9,
            },
        ],
        name: "Sports Fes 2",
        content: {
            1: {
                type: "chat",
            },
        },
    },
    {
        layout: [
            {
                x: 6,
                y: 0,
                w: 12,
                h: 12,
                i: 0,
            },
            {
                x: 6,
                y: 12,
                w: 12,
                h: 12,
                i: 1,
            },
            {
                x: 0,
                y: 0,
                w: 6,
                h: 6,
                i: 2,
            },
            {
                x: 0,
                y: 6,
                w: 6,
                h: 6,
                i: 3,
            },
            {
                x: 0,
                y: 12,
                w: 6,
                h: 6,
                i: 4,
            },
            {
                x: 0,
                y: 18,
                w: 6,
                h: 6,
                i: 5,
            },
            {
                x: 18,
                y: 0,
                w: 6,
                h: 6,
                i: 6,
            },
            {
                x: 18,
                y: 6,
                w: 6,
                h: 6,
                i: 7,
            },
            {
                x: 18,
                y: 12,
                w: 6,
                h: 6,
                i: 8,
            },
            {
                x: 18,
                y: 18,
                w: 6,
                h: 6,
                i: 9,
            },
        ],
        name: "Sports Fes 3",
        content: {},
    },
]);

export const mobilePresets = Object.freeze([
    {
        layout: [
            {
                x: 0,
                y: 0,
                w: 24,
                h: 8,
                i: 0,
            },
            {
                x: 0,
                y: 8,
                w: 24,
                h: 8,
                i: 1,
            },
            {
                x: 0,
                y: 16,
                w: 24,
                h: 8,
                i: 2,
            },
        ],
        name: "Mobile 1",
        content: {},
    },
    {
        layout: [
            {
                x: 0,
                y: 14,
                w: 24,
                h: 10,
                i: 0,
            },
            {
                x: 0,
                y: 0,
                w: 24,
                h: 7,
                i: 1,
            },
            {
                x: 0,
                y: 7,
                w: 24,
                h: 7,
                i: 2,
            },
        ],
        name: "Mobile 2",
        content: {
            0: {
                type: "chat",
            },
        },
    },
    {
        layout: [
            {
                x: 12,
                y: 0,
                w: 12,
                h: 24,
                i: 0,
            },
            {
                x: 0,
                y: 0,
                w: 12,
                h: 12,
                i: 1,
            },
            {
                x: 0,
                y: 12,
                w: 12,
                h: 12,
                i: 2,
            },
        ],
        name: "Mobile 3",
        landscape: true,
        content: {},
    },
]);
