// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/views/About.vue')['default']
    App: typeof import('./src/App.vue')['default']
    AppFrame: typeof import('./src/components/AppFrame.vue')['default']
    ArchivedTranslations: typeof import('./src/components/tldex/client/ArchivedTranslations.vue')['default']
    Button: typeof import('./src/stories/Button.vue')['default']
    ChannelImg: typeof import('./src/components/channel/common/ChannelImg.vue')['default']
    ChatMessage: typeof import('./src/components/tldex/client/ChatMessage.vue')['default']
    GoogleSignInButton: typeof import('./src/components/login/GoogleSignInButton.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HList: typeof import('./src/components/core/HList.vue')['default']
    HolodexStats: typeof import('./src/components/about/HolodexStats.vue')['default']
    Home: typeof import('./src/views/Home.vue')['default']
    HPagination: typeof import('./src/components/core/HPagination.vue')['default']
    KitchenSink: typeof import('./src/views/KitchenSink.vue')['default']
    LiveTranslations: typeof import('./src/components/tldex/client/LiveTranslations.vue')['default']
    Login: typeof import('./src/views/Login.vue')['default']
    Logo: typeof import('./src/components/frame/Logo.vue')['default']
    MainNav: typeof import('./src/components/nav/MainNav.vue')['default']
    MessageRenderer: typeof import('./src/components/tldex/client/MessageRenderer.vue')['default']
    MessageVRenderer: typeof import('./src/components/tldex/client/MessageVRenderer.vue')['default']
    NavDrawer: typeof import('./src/components/nav/NavDrawer.vue')['default']
    OrgSelector: typeof import('./src/components/frame/OrgSelector.vue')['default']
    Page: typeof import('./src/stories/Page.vue')['default']
    PageContainer: typeof import('./src/components/frame/PageContainer.vue')['default']
    PageContainerTemp: typeof import('./src/components/frame/PageContainer-temp.vue')['default']
    Profile: typeof import('./src/views/Profile.vue')['default']
    SearchBar: typeof import('./src/components/nav/SearchBar.vue')['default']
    TLClient: typeof import('./src/components/tldex/editor/TLClient.vue')['default']
    TLScriptEditor: typeof import('./src/components/tldex/editor/TLScriptEditor.vue')['default']
    TranslationClient: typeof import('./src/views/TranslationClient.vue')['default']
    TranslationScripter: typeof import('./src/views/TranslationScripter.vue')['default']
    TwitterFeed: typeof import('./src/components/about/TwitterFeed.vue')['default']
    UserCard: typeof import('./src/components/login/UserCard.vue')['default']
    VideoCard: typeof import('./src/components/video/card/VideoCard.vue')['default']
    VideoCardGrid: typeof import('./src/components/video/aggregate/VideoCardGrid.vue')['default']
    VideoCardLiveDuration: typeof import('./src/components/video/card/VideoCardLiveDuration.vue')['default']
    VideoCardMenu: typeof import('./src/components/video/card/VideoCardMenu.vue')['default']
    VideoCardStatus: typeof import('./src/components/video/card/VideoCardStatus.vue')['default']
    VideoCardText: typeof import('./src/components/video/card/VideoCardText.vue')['default']
    VideoThumbnail: typeof import('./src/components/video/card/VideoThumbnail.vue')['default']
    Watch: typeof import('./src/views/Watch.vue')['default']
  }
}
