<template>
    <div>
        <!-- watch page nav drawer is temporary, but causes layout shifting from hiding/unhiding -->
        <!-- create two different instances as a work around -->
        <NavDrawer :pages="pages" v-model="navDrawer" :temporary="isMobile || isWatchPage">
            <!-- <NavDrawer :pages="pages" v-model="drawer2" v-if="isMobile || isWatchPage"  -->
            <template v-if="isMobile">
                <InstallPrompt></InstallPrompt>
                <user-card noSetting inNavDrawer style="background-color: inherit"></user-card>
                <v-divider />
            </template>
        </NavDrawer>

        <!--* nav drawer is for the left --->
        <BottomNav :pages="pages.filter((page) => !page.collapsible)" v-if="isMobile" :active="!isWatchPage" />
        <!--* bottom bar --->
        <!-- <music-bar></music-bar> -->
        <MusicBar2 v-if="$store.state.music.isOpen" />

        <v-app-bar
            id="top-bar"
            :class="{
                'secondary darken-1': darkMode,
                'primary lighten-1': !darkMode,
            }"
            :app="!isWatchPage"
            clipped-left
            clipped-right
            flat
            v-show="!(isMobile && isWatchPage) && !isMultiView"
            extension-height="36"
        >
            <!--=============================== Top Bar (Regular View) =============================-->

            <template v-if="!isMobile || (isMobile && !searchBarExpanded)">
                <!--================= Logo & Search Bar (Space permitting) ================-->

                <v-app-bar-nav-icon @click.stop="navDrawer = !navDrawer">
                    <v-icon>{{ icons.mdiMenu }}</v-icon>
                </v-app-bar-nav-icon>
                <v-toolbar-title style="overflow: visible" :class="{ 'pa-0': isMobile }">
                    <router-link to="/">
                        <Logo width="24" height="24" style="margin-bottom: -4px" v-if="!isMobile" />
                    </router-link>
                    <OrgSelector />
                </v-toolbar-title>
                <SearchBar v-if="!isMobile" key="main-search-bar" />

                <!--================= Account [👤] Button (Desktop Only) ================-->

                <v-slide-y-transition>
                    <v-btn
                        icon
                        @click="$store.commit('music/openBar')"
                        class="music-bar-open-btn"
                        v-if="!isMobile && $store.state.music.playlist.length > 0 && !$store.state.music.isOpen"
                    >
                        <v-icon>{{ icons.mdiMusic }}</v-icon>
                    </v-btn>
                </v-slide-y-transition>
                <ResponsiveMenu
                    :close-on-content-click="false"
                    offset-y
                    :itemCount="$store.state.playlist.active.videos.length || 0"
                    contentClass="main-playlist-border"
                >
                    <template v-slot:activator="{ on, attrs }">
                        <v-btn v-bind="attrs" v-on="on" icon>
                            <v-icon>{{ icons.mdiPlaylistPlay }}</v-icon>
                        </v-btn>
                    </template>
                    <edit-playlist>
                        <div class="pt-2 pl-2">
                            <span class="text-overline secondary--text">Current Playlist</span>&emsp;
                            <a href="/playlist" class="text-caption" @click.prevent="$router.push('/playlists')">
                                (more)
                            </a>
                        </div>
                    </edit-playlist>
                </ResponsiveMenu>
                <v-menu left offset-y transition="slide-y-transition" v-if="!isMobile">
                    <template v-slot:activator="{ on, attrs }">
                        <v-btn icon v-bind="attrs" v-on="on" class="ml-2">
                            <v-icon v-if="!($store.state.userdata && $store.state.userdata.user)">{{
                                icons.mdiAccountCircleOutline
                            }}</v-icon>
                            <v-avatar size="40" v-else>
                                <img
                                    :src="`https://avatars.dicebear.com/api/jdenticon/${$store.state.userdata.user.id}.svg`"
                                    alt="Avatar generated by your user ID"
                                />
                            </v-avatar>
                        </v-btn>
                    </template>

                    <!------- USER CARD ------->
                    <user-card></user-card>
                    <!------- END USER CARD ------->
                </v-menu>

                <!--================= Search [🔍] Button (Mobile Only) ================-->

                <v-btn icon v-if="isMobile" @click="searchBarExpanded = true" class="ml-auto">
                    <v-icon>{{ icons.mdiMagnify }}</v-icon>
                </v-btn>
            </template>

            <!--=========================== END OF Regular View ===========================-->

            <!--===================== Expanded Search Bar (Mobile Only) =======================-->

            <template v-else>
                <v-app-bar-nav-icon @click="searchBarExpanded = false" class="backButton">
                    <v-icon>{{ icons.mdiClose }}</v-icon>
                </v-app-bar-nav-icon>
                <SearchBar :autofocus="isMobile" key="main-search-bar" />
            </template>

            <!--=================== END OF Expanded Search (Mobile Only) =======================-->
            <div
                :class="{
                    'secondary darken-3': darkMode,
                    'primary lighten-1': !darkMode,
                }"
                style="
                    position: absolute;
                    top: calc(-1 * env(safe-area-inset-top));
                    left: 0px;
                    right: 0px;
                    width: 100%;
                    height: env(safe-area-inset-top);
                    z-index: 300;
                "
            >
                <!-- this is just the element that covers up the notch. don't worry about it. -->
            </div>

            <!-- Extension Slot for mobile v-tabs -->
            <!-- Disable onScroll when ext is disabled. onScroll hooks on to window, so it can live anywhere -->
            <span v-if="!disableExt" v-scroll="onScroll" />
            <template v-slot:extension v-if="!disableExt">
                <v-slide-y-transition>
                    <!-- v-tabs are teleported here from their respective view -->
                    <portal-target name="mainNavExt" slim v-if="showExt"> </portal-target>
                </v-slide-y-transition>
            </template>
        </v-app-bar>
    </div>
</template>

<script lang="ts">
import SearchBar from "@/components/common/SearchBar.vue";
import Logo from "@/components/common/Logo.vue";
import OrgSelector from "@/components/common/OrgSelector.vue";
import UserCard from "@/components/user/UserCard.vue";
import { mdiInfinity } from "@mdi/js";
import { mapState } from "vuex";
import InstallPrompt from "@/components/common/InstallPrompt.vue";
import hideExtensionOnScroll from "@/mixins/hideExtensionOnScroll";
import EditPlaylist from "@/components/playlist/EditPlaylist.vue";
import ResponsiveMenu from "@/components/common/ResponsiveMenu.vue";
import NavDrawer from "./NavDrawer.vue";
import BottomNav from "./BottomNav.vue";

export default {
    components: {
        SearchBar,
        NavDrawer,
        BottomNav,
        UserCard,
        Logo,
        InstallPrompt,
        MusicBar2: () => import("./MusicBar2.vue"),
        OrgSelector,
        EditPlaylist,
        ResponsiveMenu,
    },
    mixins: [hideExtensionOnScroll],
    data() {
        return {
            favoritesExpanded: false,
            searchBarExpanded: false,
        };
    },
    computed: {
        isMobile() {
            return this.$store.state.isMobile;
        },
        darkMode() {
            return this.$store.state.settings.darkMode;
        },
        isWatchPage() {
            return ["watch_id", "watch", "mugen-clips", "edit_video", "multiview"].includes(this.$route.name);
        },
        isMultiView() {
            return this.$route.name === "multiview";
        },
        navDrawer: {
            get() {
                return this.$store.state.navDrawer;
            },
            set(val) {
                return this.$store.commit("setNavDrawer", val);
            },
        },
        pages() {
            return [
                {
                    name: this.$t("component.mainNav.home"),
                    path: "/home",
                    icon: this.icons.mdiHome,
                },
                {
                    name: this.$t("component.mainNav.favorites"),
                    path: "/favorites",
                    icon: this.icons.mdiHeart,
                },
                {
                    name: this.$t("component.mainNav.channels"),
                    path: "/channel",
                    icon: this.icons.mdiAccountBoxMultiple,
                },
                {
                    name: this.$t("component.mainNav.playlist"),
                    path: "/playlists",
                    icon: this.icons.mdiPlaylistPlay,
                    divider: true,
                },
                {
                    name: this.$t("component.mainNav.multiview"),
                    path: "/multiview",
                    icon: this.icons.mdiViewDashboard,
                    collapsible: true,
                },
                {
                    name: this.$t("component.mainNav.music"),
                    path: "/music",
                    icon: this.icons.mdiMusic,
                    collapsible: true,
                },
                {
                    name: this.$t("component.mainNav.MugenClips"),
                    path: "/infinite",
                    icon: mdiInfinity,
                    collapsible: true,
                    divider: true,
                },
                {
                    name: this.$t("component.mainNav.about"),
                    path: "/about",
                    icon: this.icons.mdiHelpCircle,
                    collapsible: true,
                },
                {
                    name: this.$t("component.mainNav.settings"),
                    path: "/settings",
                    icon: this.icons.mdiCog,
                    collapsible: true,
                },
            ];
        },
        // getHeight() {
        //     console.log(this.$vuetify.breakpoint.width);
        //     // ^ very important, causes the function to link reactivity to width changes.
        //     return Number.parseFloat(
        //         getComputedStyle(document.documentElement).getPropertyValue("--sat")) / 1.5 + 64;
        // },
        ...mapState(["firstVisit"]),
    },
    created() {
        if (this.$store.state.firstVisit) {
            const vm = this;
            setTimeout(() => {
                vm.$store.commit("setVisited");
            }, 30000);
        }

        // always pop out nav drawer if it's not watch page or collapsed
        if (
            !window.location.pathname.match("^/watch|^/multiview|^/infinite") &&
            !this.isMobile &&
            !this.$vuetify.breakpoint.md
        ) {
            this.navDrawer = true;
        }
    },
    watch: {
        // toggle navdrawer when navigating between watch pages on desktop
        isWatchPage() {
            if (this.isMobile) return;
            this.navDrawer = !this.isWatchPage;
        },
        // if user is flipping between mobile/desktop breakpoints, keep navdrawer closed
        isMobile() {
            this.navDrawer = false;
        },
    },
};
</script>

<style scoped>
@keyframes rotation {
    from {
        transform: rotate(0deg);
    }
    to {
        transform: rotate(359deg);
    }
}

#top-bar {
    /* background-color: #2b79ad !important; */
    padding-left: min(calc(env(safe-area-inset-left)), 30px);
    padding-right: min(calc(env(safe-area-inset-right)), 30px);
    /* padding-top: min(calc(env(safe-area-inset-top) / 2), 30px); */
    /* height: calc(env(safe-area-inset-top,0px) + 30px); */
    padding-top: 0px;
    margin-top: env(safe-area-inset-top, 0px) !important;
}
#top-bar.v-toolbar--extended {
    height: 56px !important;
}

.fade-enter-active,
.fade-leave-active {
    transition: opacity 0.3s ease;
}
.fade-enter,
.fade-leave-to {
    opacity: 0;
}

.music-bar-open-btn {
    animation-timing-function: ease-in-out;
    animation: fadein 5s;
    animation-iteration-count: 1;
}

.main-playlist-border {
    border: 2px solid var(--v-primary-base);
    border-radius: 8px;
}
.theme--dark .main-playlist-border {
    box-shadow: 0px 6px 12px -7px var(--v-primary-darken2);
}
.theme--light .main-playlist-border {
    box-shadow: 0px 6px 12px -7px var(--v-primary-lighten2);
}
</style>
