name: Deploy to next

on:
  push:
    branches:
      - next

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy next
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            export NVM_DIR="$HOME/.nvm"
            if [ -s "$NVM_DIR/nvm.sh" ]; then
              . "$NVM_DIR/nvm.sh"
              echo "NVM loaded successfully."
            else
              echo "Error: NVM not found at $NVM_DIR"
              exit 1
            fi
            cd /opt/next_web/packages/react || { echo "No directory found"; exit 1; } 
            nvm use
            git pull origin next
            npm ci
            npm run build
            rm -r /var/www/html/next.holodex.net/*
            cp -r dist/* /var/www/html/next.holodex.net/
